language: java
jdk:
  - oraclejdk8
  - openjdk7
cache:
  directories:
  - "$HOME/.cache"
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
#script: mvn clean test --settings ".travis.settings.xml"
#deploy: mvn deploy -DskipTests=true --settings ".travis.settings.xml"
